package pt.ulusofona.aed.rockindeisi2023;

public enum QuerysEnum
{
    COUNT_SONGS_YEAR,
    GET_SONGS_BY_ARTIST,
    GET_MOST_DANCEABLE,
    ADD_TAGS,
    REMOVE_TAGS,
    GET_ARTISTS_FOR_TAG,
    GET_TOP_ARTISTS_WITH_SONGS_BETWEEN,
    COUNT_DUPLICATE_SONGS_YEAR,
    GET_ARTISTS_ONE_SONG,
    MOST_FREQUENT_WORDS_IN_ARTIST_NAME,
    GET_UNIQUE_TAGS,
    GET_UNIQUE_TAGS_IN_BETWEEN_YEARS,
    GET_RISING_STARS,
    GET_SONGS_BETWEEN_YEARS,

    EXIT
}